lynxtoys/config/routes.rb
Rails.application.routes.draw do
  
  resources :creations do
    member do
      get 'upvote'
    end
  end

  get 'creations/new' => 'creations#new'

  get 'welcome/index'
  root 'welcome#index'
  get 'creations/index' => 'creations#index'
  get 'creations/:id/delete' => 'creations#delete', :as => :creations_delete
  get 'securemanage_lynxtoys/:id/manage' => 'creations#manage', :as => :creations_manage
  get 'securemanage_lynxtoys/:id/accept' => 'creations#accept', :as => :creations_accept

end

lynxtoys/app/models/cover.rb
class Cover < ActiveRecord::Base
	belongs_to :creation
	has_attached_file :cover, :path => ":rails_root/public/covers/:id_:filename", :url  => "/covers/:id_:filename"
	do_not_validate_attachment_file_type :cover
end

lynxtoys/app/models/creation.rb
class Creation<ActiveRecord::Base
    has_many :pictures, :dependent=>:destroy
    has_many :votes, :dependent=>:destroy
    #before_destroy :ensure_not_referenced_by_any_picture
    has_one :cover, :dependent=>:destroy
    #has_attached_file :image
    #has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
    #validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
	
    def ensure_not_referenced_by_any_pircture
        if pictures.count.zero?
           return true
        else
            errors[:base]<<"Pictures present"
            return false
        end
    end
	
end

lynxtoys/app/models/picture.rb
class Picture < ActiveRecord::Base
	belongs_to :creation
	has_attached_file :image, :path => ":rails_root/public/images/:id_:filename", :url  => "/images/:id_:filename"
	do_not_validate_attachment_file_type :image	
	validates :creation_id, :presence => true
	validates_associated :creation    
end

lynxtoys/app/models/vote.rb
class Vote < ActiveRecord::Base
    belongs_to :creation
    
end

lynxtoys/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

lynxtoys/app/controllers/backup/creation_controller.rb
class CreationController < ApplicationController
  def index
	@creations = Creation.first
	@id = @creations.creation_id
	@pictures = Picture.where(creation_id: @id)
  end
  
  def new
	@creation = Creation.new
  end
  
  def create
    @creation = Creation.new(category_params)
    if @creation.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end
  
  def show
	@creation = Creation.find(params[:id])
  end
  
  private
  
  def creation_params
	params.require(:creation).permit(:name)
  end
end

lynxtoys/app/controllers/creations_controller.rb
class CreationsController < ApplicationController
  #def index
#	@creations = Creation.first
#	@id = @creations.creation_id
#	@pictures = Picture.where(creation_id: @id)
#  end
  def index
    @creations = Creation.all
    @sortCriteria = nil
    if params[:sort] != nil
      @sortCriteria = params[:sort]
    end
    if @sortCriteria == 'votes-rank'
      @creations = @creations.sort {|a,b| b.votes.count <=> a.votes.count}
    else
      @creations = @creations.sort {|a,b| b.created_at <=> a.created_at}
    end
  end
  
  def new
    @creation = Creation.new
  end
  
  def create
  	@creation = Creation.new(creation_params)
	@host = request.host
	@port = request.port
	if @port == 443
		@url = "https://"+@host
	else
		@url = "http://"+@host+":"+String(@port)
	end
    if !verify_recaptcha(model: @creation, private_key: "6LciMwUTAAAAAHFDUOFGVx58aY66C_Bw5FZQ6Yt7") 
      flash[:warning] = "The data you entered for the CAPTCHA wasn't correct.  Please try again"
      redirect_to new_creation_path
    elsif @creation.email != "" and not is_a_valid_email?(@creation.email)
		flash[:warning] = "Invalid email address.  Please input a valid email"
      	redirect_to new_creation_path
	else
      flash[:notice] = 'Creation was successfully uploaded and will be available for viewing once approved.'
      respond_to do |format|
      	if @creation.save
      		if params[:images]
      	 	  params[:images].each { |image|
      			@creation.pictures.create(image: image)
      		  }
      		end
      		#@creation.cover.create(cover: params[:cover])
      		@cover = Cover.new
      		@cover.cover=params[:cover]
      		@cover.creation_id=@creation.id
      		@cover.save
      		format.html { redirect_to @creation }
          	format.json { render json: @creation, status: :created, location: @creation }
      	else
      		format.html { render action: "new" }
      	      #format.json { render json: @creation.errors, status: :unprocessable_entity }
      	end	
      end
      ManageMailer.email_to_manager(@creation,@url).deliver
	  if @creation.email != ""
	  	ManageMailer.email_to_user(@creation,"created",@url).deliver
	  end
    end
  end
  
  def show
	@creation = Creation.find(params[:id])
  end

  def manage
	@creation = Creation.find(params[:id])
  end
  
  def accept
	@creation = Creation.find(params[:id])
	@creation.isAc = 1
	@creation.save
	@host = request.host
	@port = request.port
	@host = request.host
	@port = request.port
	if @port == 443
		@url = "https://"+@host
	else
		@url = "http://"+@host+":"+String(@port)
	end
	if @creation.email != ""
		ManageMailer.email_to_user(@creation,"accepted",@url).deliver
	end
	redirect_to creations_path
  end
 
  def delete
    @creation = Creation.find(params[:id])
    @creation.pictures.each do |picture|
		picture.image=nil
	end
	@creation.cover=nil
	@creation.save
	@creation.destroy
	@host = request.host
	@port = request.port
	@host = request.host
	@port = request.port
	if @port == 443
		@url = "https://"+@host
	else
		@url = "http://"+@host+":"+String(@port)
	end
    flash[:notice] = "Creation '#{@creation.name}' deleted."
	if @creation.email != ""
		ManageMailer.email_to_user(@creation,"rejected",@url).deliver
	end
    redirect_to creations_path
  end

  #def destroy
	#Creation.find(params[:id]).destroy
	#redirect_to(:action => 'index')
  #end

  def upvote
     flag = 0
     @creation = Creation.find(params[:id])
     @creation.votes.each do |v|
	if(v.vote_ip == request.remote_ip)
		flag = 1;
        end
     end
     if(flag == 0)
     	@creation.votes.create(vote_ip: request.remote_ip)
	flash[:notice] = 'Thanks for your voting!'
     else
        flash[:notice] = 'You have voted this creation!'
     end
     redirect_to creation_path(@creation)
  end
  
  private
  
  def creation_params
	params.require(:creation).permit(:name,:creator_name,:description,:likes,:email)
  end
 def is_a_valid_email?(email)
  email.match(/^[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]$/i) != nil
 end
end

lynxtoys/app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
	@pictures = Picture.find_by_sql("SELECT * FROM pictures")
  end
  def new
	@picture = Picture.new
  end
  #def create
#	@picture = Picture.new(picture_params)
 # end
end

lynxtoys/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

lynxtoys/app/helpers/application_helper.rb
module ApplicationHelper
end

lynxtoys/app/helpers/creation_helper.rb
module CreationHelper
end

lynxtoys/app/helpers/creations_helper.rb
module CreationsHelper
end

lynxtoys/app/helpers/pictures_helper.rb
module PicturesHelper
end

lynxtoys/app/helpers/welcom_helper.rb
module WelcomHelper
end

lynxtoys/app/views/creations/_form.html.erb
<html>
<%= form_for @creation, :url => creations_path, :html => { :class => 'form-horizontal', multipart: true } do |f| %>

  <%= f.label "Creation Name (required)", :style => 'font-size: 200%; color: white; margin-bottom: -4%' %>

  <%= f.text_field :name, required: true, :style => 'background-color: #474747' %>

  <%= f.label :creator_name, :style => 'font-size: 200%; color: white; margin-bottom: -4%' %>

  <%= f.text_field :creator_name, :style => 'background-color: #474747' %>

  <%= f.label :description, :style => 'font-size: 200%; color: white; margin-bottom: -4%' %>

  <%= f.text_field :description, :style => 'background-color: #474747' %>

  <%= f.label "Email (to be notified for acceptance of creation)", :style => 'font-size: 200%; color: white; margin-bottom: -4%' %>

  <%= f.text_field :email, :style => 'background-color: #474747' %>

  <div class="control-group">
    <%= f.label "Main Photo (required)", :class => 'control-label', :style => 'font-size: 200%; color: white' %>
    <%= file_field_tag "cover", type: :file, id: 'CoverToUpload', :onchange => "check_file('CoverToUpload')", :required => true, style: 'font-size: 200%; background-color: white' %>

    <%= f.label "More Photos", :style => 'font-size: 200%; color: white' %>
    <div class="controls">
      <!-- The magic is coming ...look at my eyes....shazammmm -->
      <!-- Use HTML5 multiple attribute to enable multiple selection
           and pass back to controller all files as an array, ready 
           for paperclip!!
           file_field_tag, since images is not a gallery attribute
       -->
      <%= file_field_tag "images[]", type: :file, id: 'ImagesToUpload', :onchange => "check_file('ImagesToUpload')", multiple: true, style: 'font-size: 200%; background-color: white' %>
    </div>
  </div>
  <div class="recaptcha_area">
     <%= recaptcha_tags %>
  </div>
  <div class="form-actions">
    <%= f.submit "Submit Creation", :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                creations_path, :class => 'btn btn-mini' %>
  </div>
<% end %>

<script>
$(document).ready(function(){
    $("input").focus(function(){
        $(this).css("background-color", "#cccccc");
    });
    $("input").blur(function(){
        $(this).css("background-color", "#474747");
    });
});
function check_file(id){
                selection=document.getElementById(id);
				//window.alert(selection)
        for (var i=0; i<selection.files.length; i++) {
    var ext = selection.files[i].name.substr(selection.files[i].name.lastIndexOf('.')+1).toLowerCase();
    if(ext!== "jpg" && ext!== "jpeg" && ext!== "png" && ext!== "gif") {
        alert('only support jpg/jpeg/png/gif format');
		document.getElementById(id).value='';
        return false;
    }
    }
	}
</script>
</html>

lynxtoys/app/views/creations/_form_sort.html.erb
<form id="sortForm" method="get" action="creations" style='float: right'>
    <span class="">Sort by&nbsp;</span>
    <select class="" style="vertical-align: baseline;" name="sort" id="sort" onchange="this.form.submit();">
        <% if @sortCriteria == 'votes-rank' %>
            <option value="votes-rank">Most Upvoted</option>
            <option value="time-rank">Most Recent</option>
        <% else %>
            <option value="time-rank">Most Recent</option>
            <option value="votes-rank">Most Upvoted</option>
        <% end %>
    </select>
</form>

lynxtoys/app/views/creations/index.html.erb
<html>
<h2 class="style">Explore the creations from our community</h2>
<h3 style="margin: -2% 4% 2%;">
  <span style='float: left;'><%= button_to "New Creation", creations_new_path, :method => :get, :class => 'btn btn-primary btn-lg', :style => 'background: #2EB398;' %></span>
  <%=render 'form_sort' %>
</h3>
  <div class="main row">
     <% count=-1 %>
      <% @creations.each do |creation| %>
        <% if creation.isAc ==1 %>
          <% count=count+1 %>
          <% if count%4==0 %>
            <div class="grids_of_4 row">
          <% end %>
          <div class="col-md-3 images_1_of_4">
            <div class="fancyDemo">
              <a rel="group" title="" href=<%= creation_path(creation) %>>
                 <% unless creation.cover.nil? %>
                    <%= image_tag creation.cover.cover.url, class: "img-responsive" %>
                 <% end %>
              </a>
              <p class="para"><%= creation.name %></p>
            </div> 
          </div>
          <% if count%4==3 %>
            </div>
          <% end %>

        <% end %>


      <% end %>

      <% if count%4!=3 %>
            </div>

      <% end %> 
</html> 

lynxtoys/app/views/creations/manage.html.erb
<h4><%= link_to 'Accept', creations_accept_path(@creation) %>&nbsp&nbsp&nbsp&nbsp<%= link_to 'Reject', creations_delete_path(@creation) %></h4>
<h4><%= "Creation Name: "+@creation.name %></h4>
<% count=0 %>
<div class="grids_of_4 row">
  <div class="col-md-3 images_1_of_4">
    <div class="fancyDemo">
      <a class="fancybox-thumbs" rel="gallery1" href=<%= @creation.cover.cover.url %> data-fancybox-group="gallery" title=""><img src=<%= @creation.cover.cover.url %> class="img-responsive" alt="" /></a>
    </div>
  </div>
       
  <% @creation.pictures.each do |p| %>
    <% count=count+1 %>
    <% if count%4==0 %>
            <div class="grids_of_4 row">
    <% end %>
    <div class="col-md-3 images_1_of_4">
      <div class="fancyDemo">
        <a class="fancybox-thumbs" rel="gallery1" href=<%= p.image.url %> data-fancybox-group="gallery" title=""><img src=<%= p.image.url %> class="img-responsive" alt="" /></a >
      </div>
    </div>
    <% if count%4==3 %>
      </div>
    <% end %>
  <% end %>
<% if count%4!=3 %>
  </div>
<% end %>




lynxtoys/app/views/creations/new.html.erb
<body style="background: #353535">
<h2 class="style">Create a new creation</h3>
<div class="container">
  <div style="background: #353535">
    <div class="col-md-8 contact_left">
      <%= render 'form' %>
    </div>
  </div>
</div>
</body>

lynxtoys/app/views/creations/show.html.erb
<html>
<h4><%= "Creation Name: "+@creation.name%></h4>
<h4><%= "Creator Name: "+@creation.creator_name%></h4>
<h4><%= "Description: "+@creation.description%></h4>

<tr>
   <td><% pluralize(@creation.votes.count, "vote") %></td>
   <td><% button_to '+1', upvote_creation_path(@creation), method: :post %></td>
</tr>
<% count=0 %>
<div class="grids_of_4 row">
  <div class="col-md-3 images_1_of_4">
    <div class="fancyDemo">
      <!-- a rel="group" title="" href=<%= @creation.cover.cover.url %>><%= image_tag @creation.cover.cover.url, class: "img-responsive" %></a -->
     <a class="fancybox-thumbs" rel="gallery1" href=<%= @creation.cover.cover.url %> data-fancybox-group="gallery" title=""><img src=<%= @creation.cover.cover.url %> class="img-responsive" alt="" /></a>
    </div>
  </div>
       
  <% @creation.pictures.each do |p| %>
    <% count=count+1 %>
    <% if count%4==0 %>
            <div class="grids_of_4 row">
    <% end %>
    <div class="col-md-3 images_1_of_4">
      <div class="fancyDemo">
	<a class="fancybox-thumbs" rel="gallery1" href=<%= p.image.url %> data-fancybox-group="gallery" title=""><img src=<%= p.image.url %> class="img-responsive" alt="" /></a >
	<!-- a class="fancybox-effects-a" href=<%= p.image.url %> title="Lorem ipsum dolor sit amet, consectetur adipiscing elit"><img src=href=<%= p.image.url %> alt="" /></a -->
        <!-- a rel="group" title="" href=<%= p.image.url %>><%= image_tag p.image.url, class: "img-responsive" %></a -->
      </div>
    </div>
    <% if count%4==3 %>
      </div>
    <% end %>
  <% end %>
<% if count%4!=3 %>
  </div>
<% end %>

<h4><%= link_to image_tag("/images/upvote.jpg", size: "70x70"), upvote_creation_path(@creation) %>
<%= pluralize(@creation.votes.count, "vote") %></h4>

<h3>Share this creation!</h3>
<link href="/assets/sharebutton.css" rel='stylesheet' type='text/css' />
<h4><% render_shareable :buttons=> ['twitter', 'facebook', 'tumblr', 'google_plus','linkedin'] %></h4>

<div id="share-buttons">
<% share_url = request.original_url %>
<!-- Facebook -->
<a href="http://www.facebook.com/sharer.php?u=#{share_url}" target="_blank"><img src="/assets/facebook.png" alt="Facebook" /></a>
<!-- Twitter -->
<a href="http://twitter.com/share?url=#{share_url}&text=Lyntoys&hashtags=simplesharebuttons" target="_blank"><img src="/assets/twitter.png" alt="Twitter" /></a>
<!-- Google+ -->
<a href="https://plus.google.com/share?url=#{share_url}" target="_blank"><img src="/assets/google.png" alt="Google" /></a>
<!-- Digg -->
<a href="http://www.digg.com/submit?url=#{share_url}" target="_blank"><img src="/assets/diggit.png" alt="Digg" /></a>
<!-- Reddit -->
<a href="http://reddit.com/submit?url=#{share_url}&title=Lyntoys" target="_blank"><img src="/assets/reddit.png" alt="Reddit" /></a>
<!-- LinkedIn -->
<a href="http://www.linkedin.com/shareArticle?mini=true&url=#{share_url}" target="_blank"><img src="/assets/linkedin.png" alt="LinkedIn" /></a>
<!-- Pinterest -->
<a href="javascript:void((function()%7Bvar%20e=document.createElement('script');e.setAttribute('type','text/javascript');e.setAttribute('charset','UTF-8');e.setAttribute('src','http://assets.pinterest.com/js/pinmarklet.js?r='+Math.random()*99999999);document.body.appendChild(e)%7D)());"><img src="/assets/pinterest.png" alt="Pinterest" /></a>
<!-- StumbleUpon-->
<a href="http://www.stumbleupon.com/submit?url=#{share_url}&title=Simple Share Buttons" target="_blank"><img src="/assets/stumbleupon.png" alt="StumbleUpon" /></a>
<!-- Email -->
<a href="mailto:?Subject=Simple Share Buttons&Body=I%20saw%20this%20and%20thought%20of%20you!%20 #{share_url}"><img src="/assets/email.png" alt="Email" /></a>
</div> 
</html>

lynxtoys/app/views/pictures/index.html.haml
%h1 Pictures#index

%tbody
	-@pictures.each do |picture|
		=image_tag picture.url
		<br>

lynxtoys/app/views/welcome/index.html.erb
<div class="slider_bg"><!-- start slider -->
<div class="container">
		<div class="row slider">
		<div class="wmuSlider example1"><!-- start wmuSlider example1 -->
			   <div class="wmuSliderWrapper">
				   <article style="position: absolute; width: 100%; opacity: 0;"> 
				  	 	<div class="slider_img text-center">
				   			<ul class="list-unstyled list_imgs">
				   				<li><img src="/assets/slider.jpg" alt="" class="responsive"/></li>
				   			</ul>
			           	</div>
				   </article>
				   <!-- <article style="position: relative; width: 100%; opacity: 1;"> 
				  	 	<div class="slider_img text-center">
				   			<ul class="list-unstyled list_imgs">
				   				<li><img src="/assets/slider1.jpg" alt="" class="responsive"/></li>
				   			</ul>
			           	</div>
				   </article> -->
				 </div>
                <ul class="wmuSliderPagination">
                	<li><a href="#" class="">0</a></li>
                	<!-- <li><a href="#" class="">1</a></li> -->
                </ul>
			<script src="/assets/jquery.wmuSlider.js"></script> 
		     <script>
				 $('.example1').wmuSlider();         
			</script>
        </div><!-- end wmuSlider example1 -->
        <div class="clearfix"></div>
      </div>
</div>
</div>
<div class="main_bg"  id="buynow"><!-- start buy now -->
<div class="container">
	<div class="row about">
		<div class="col-md-3 about_img">
			<img src="/assets/boxes.png" alt="" class="responsive"/>
		</div>
		<div class="col-md-9 about_text">
			<h3>Lynx Toys</h3>
			<h4>Creation! Innovation! Imagination!</h4>
			<p>Use your noodles to build anything! Each box of Lynx includes 12 connectors. Fun for in <b>and</b> out of the pool &#8211; use your noodles all year long!<br><br></p>
			<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
				<input type="hidden" name="cmd" value="_s-xclick">
				<input type="hidden" name="hosted_button_id" value="KAWQAQ68WXXS2">
				<input type="image" src="/assets/buynow.png" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
				<img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
			</form>

			<div class="soc_icons navbar-right">
				<ul class="list-unstyled text-center">
					<li><a href="http://www.facebook.com/lynxtoysllc"><i class="fa fa-facebook"></i></a></li>
					<li><a href="http://www.instagram.com/lynxtoys"><i class="fa fa-instagram"></i></a></li>
					<li><a href="http://www.twitter.com/lynxtoys"><i class="fa fa-twitter"></i></a></li>
					<li><a href="http://www.linkedin.com/company/lynx-toys"><i class="fa fa-linkedin"></i></a></li>
				</ul>	
			</div>
		</div>
	</div>
</div>
</div>

<div class="footer_bg" id="reviews"><!-- start footer (reviews) -->
<div class="container">
		<div class="col-md-8 contact_left">
			<br><br>
			<h3>It is an amazing idea!</h3>
			<p>"I bought a set before Christmas and took them to my grandchildren in Singapore where they can swim everyday in 86 degree weather. They loved them." - Rodney H.</h4><br><br>
			<h3>Great toy!</h3>
			<p>"This is one of my favorite new outdoor toys. I live in Texas and am usually beat by the heat, but this toy lets me get out side and be creative. I would highly recommend this toy to everyone with a pool in their backyard." - Jake W.</h4><br><br>
			<h3>Five stars!</h3>
			<p>"Kids had a blast." - Suzanne P.</h4><br><br>
		</div>
		<div class="col-md-4  contact_right">
			<img src="/assets/lynx-part.png">
		</div>		
</div>
</div>

lynxtoys/app/views/welcome1/index.html.erb
<h1>Hello, word</h1>